const http = require("http");
const menData= [
    {
        "id":"1",
        "name":"Tshirt",
        "brand":"Gucci",
        "price":2000,
        "color":"black",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"2",
        "name":"Shirt",
        "brand":"Zara",
        "price":3000,
        "color":"blue",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"3",
        "name":"Jeans",
        "brand":"Gucci",
        "price":2500,
        "color":"black",
        "size":"L",
        "category":"Clothing"
    },
    {
        "id":"4",
        "name":"Tshirt",
        "brand":"Gucci",
        "price":2000,
        "color":"red",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"5",
        "name":"Trouser",
        "brand":"H&M",
        "price":5000,
        "color":"black",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"6",
        "name":"Shirt",
        "brand":"Gucci",
        "price":6000,
        "color":"black",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"7",
        "name":"Suit",
        "brand":"Gucci",
        "price":12000,
        "color":"black",
        "size":"L",
        "category":"Clothing"
    },
    {
        "id":"8",
        "name":"Tshirt",
        "brand":"Gucci",
        "price":2000,
        "color":"blue",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"9",
        "name":"Tshirt",
        "brand":"Gucci",
        "price":2000,
        "color":"purple",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"10",
        "name":"Tshirt",
        "brand":"Deor",
        "price":2000,
        "color":"black",
        "size":"M",
        "category":"Clothing"
    }
]
const womenData= [
    {
        "id":"1",
        "name":"Tshirt",
        "brand":"Gucci",
        "price":2000,
        "color":"black",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"2",
        "name":"jeans",
        "brand":"Zara",
        "price":3000,
        "color":"blue",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"3",
        "name":"Froak",
        "brand":"Gucci",
        "price":2500,
        "color":"black",
        "size":"L",
        "category":"Clothing"
    },
    {
        "id":"4",
        "name":"skirt",
        "brand":"Gucci",
        "price":2000,
        "color":"red",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"5",
        "name":"Suit",
        "brand":"H&M",
        "price":5000,
        "color":"black",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"6",
        "name":"Lehnga",
        "brand":"Gucci",
        "price":6000,
        "color":"black",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"7",
        "name":"Suit",
        "brand":"Gucci",
        "price":12000,
        "color":"black",
        "size":"L",
        "category":"Clothing"
    },
    {
        "id":"8",
        "name":"Tshirt",
        "brand":"Gucci",
        "price":2000,
        "color":"blue",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"9",
        "name":"Tshirt",
        "brand":"Gucci",
        "price":2000,
        "color":"purple",
        "size":"M",
        "category":"Clothing"
    },
    {
        "id":"10",
        "name":"Tshirt",
        "brand":"Deor",
        "price":2000,
        "color":"black",
        "size":"M",
        "category":"Clothing"
    }
]

const server=http.createServer((req,res)=>{
    if (req.url=="/") {
        res.end("Welcome to Men & Woman Dummy Data");
    }
    else if (req.url=="/men"){
        res.end(JSON.stringify(menData));
    }
    else if (req.url=="/woman"){
        res.end(JSON.stringify(womenData));
    }else{
        res.end("Page not found");
    }
})

server.listen(3000,()=>{
    console.log("server started at port 3000");
})

